#!/usr/bin/env ruby 


#puts "Example: 0x7c86fed3"

ret = ARGV[0].chomp
ret = ret.hex
#ret = 0x7c86fed3
newret = ([ret].pack('V')).unpack('H*').first
finalret = newret.scan(/.{2}/)

$i = 0

#puts "The new value is... "
while $i < finalret.length do
  print '\x'+finalret[$i]
  $i +=1
end
puts
