#!/usr/bin/env python
__author__ = 'admanne'
import sys
import os

if len(sys.argv) != 3:
    print "<address-range> <ports>"
    print "Example:  null_enum_http 192.168.15.200-254 80,8080,443,4443,7778,5357,10000"
    sys.exit(0)

address = sys.argv[1].strip()
port = sys.argv[2].strip()
# Enum
# -sS/sT/sA/sW/sM: TCP SYN/Connect()/ACK/Window/Maimon scans
# default sT
enum = (
    "xterm -e \"nmap -sV -sT -Pn -vv -p %s --script=http-huawei-hg5xx-vuln,http-iis-webdav-vuln,http-vmware-path-vuln,http-vuln-cve2009-3960,"
    "http-vuln-cve2010-0738,http-vuln-cve2010-2861,http-vuln-cve2011-3192,http-vuln-cve2011-3368,http-vuln-cve2012-1823,"
    "http-vuln-cve2013-0156 -oX 'enum_http_%s.xml' -oN 'enum_http_%s.nmap' %s\" &" % (
        port, address, address, address))
print enum
os.system(enum)

# http-adobe-coldfusion-apsa1301.nse
# http-affiliate-id.nse
# http-apache-negotiation.nse
# http-auth-finder.nse
# http-auth.nse
# http-awstatstotals-exec.nse
# http-axis2-dir-traversal.nse
# http-backup-finder.nse
# http-barracuda-dir-traversal.nse
# http-brute.nse
# http-cakephp-version.nse
# http-chrono.nse
# http-coldfusion-subzero.nse
# http-comments-displayer.nse
# http-config-backup.nse
# http-cors.nse
# http-csrf.nse
# http-date.nse
# http-default-accounts.nse
# http-devframework.nse
# http-dlink-backdoor.nse
# http-dombased-xss.nse
# http-domino-enum-passwords.nse
# http-drupal-enum-users.nse
# http-drupal-modules.nse
# http-email-harvest.nse
# http-enum.nse
# http-errors.nse
# http-exif-spider.nse
# http-favicon.nse
# http-feed.nse
# http-fileupload-exploiter.nse
# http-form-brute.nse
# http-form-fuzzer.nse
# http-frontpage-login.nse
# http-generator.nse
# http-git.nse
# http-gitweb-projects-enum.nse
# http-google-malware.nse
# http-grep.nse
# http-headers.nse
# http-huawei-hg5xx-vuln.nse
# http-icloud-findmyiphone.nse
# http-icloud-sendmsg.nse
# http-iis-short-name-brute.nse
# http-iis-webdav-vuln.nse
# http-joomla-brute.nse
# http-litespeed-sourcecode-download.nse
# http-majordomo2-dir-traversal.nse
# http-malware-host.nse
# http-methods.nse
# http-method-tamper.nse
# http-mobileversion-checker.nse
# http-ntlm-info.nse
# http-open-proxy.nse
# http-open-redirect.nse
# http-passwd.nse
# http-phpmyadmin-dir-traversal.nse
# http-phpself-xss.nse
# http-php-version.nse
# http-proxy-brute.nse
# http-put.nse
# http-qnap-nas-info.nse
# http-referer-checker.nse
# http-rfi-spider.nse
# http-robots.txt.nse
# http-robtex-reverse-ip.nse
# http-robtex-shared-ns.nse
# http-server-header.nse
# http-sitemap-generator.nse
# http-slowloris-check.nse
# http-slowloris.nse
# http-sql-injection.nse
# http-stored-xss.nse
# http-title.nse
# http-tplink-dir-traversal.nse
# http-trace.nse
# http-traceroute.nse
# http-unsafe-output-escaping.nse
# http-useragent-tester.nse
# http-userdir-enum.nse
# http-vhosts.nse
# http-virustotal.nse
# http-vlcstreamer-ls.nse
# http-vmware-path-vuln.nse
# http-vuln-cve2009-3960.nse
# http-vuln-cve2010-0738.nse
# http-vuln-cve2010-2861.nse
# http-vuln-cve2011-3192.nse
# http-vuln-cve2011-3368.nse
# http-vuln-cve2012-1823.nse
# http-vuln-cve2013-0156.nse
# http-vuln-zimbra-lfi.nse
# http-waf-detect.nse
# http-waf-fingerprint.nse
# http-wordpress-brute.nse
# http-wordpress-enum.nse
# http-wordpress-plugins.nse
# http-xssed.nse
# membase-http-info.nse
# riak-http-info.nse
