#!/usr/bin/env python
__author__ = 'admanne'
import sys
import os

if len(sys.argv) != 3:
    print "<address-range> <ports>"
    print "Example:  null_enum_ftp 192.168.15.200-254 21,2100,2121"
    sys.exit(0)

address = sys.argv[1].strip()
port = sys.argv[2].strip()
# Enum
os.system(
    "xterm -e \"nmap -sV -Pn -vv -p %s --script=ftp-anon,ftp-bounce,ftp-libopie,ftp-proftpd-backdoor,ftp-vsftpd-backdoor,ftp-vuln-cve2010-4221 -oX 'enum_ftp_%s.xml' -oN 'enum_ftp_%s.nmap' %s\" &" % (
    port, address, address, address))