#!/usr/bin/python
#
__author__ = 'admanne'
import os
import os.path
import sys
import datetime
import time
import threading

#  cat 192.168.15.238.dirb | grep '+\|DIRECTORY' | sort -u

if len(sys.argv) != 3:
    print "Usage: dirbust.py -t/T target/s"
    print "Example null_dirb -t 192.168.15.205"
    sys.exit(0)

t_switch = str(sys.argv[1])
targets = str(sys.argv[2])

folders = ["/usr/share/dirb/wordlists/", "/usr/share/dirb/wordlists/vulns/"]

def dirb_thread(command_chain, blank):
    os.system(command_chain)

out_put_files = []
f = []
if t_switch.strip() == "-T":
    f = [line.strip() for line in open(targets)]
if t_switch.strip() == "-t":
    f.append(targets)

for address in f:
    if address[:4] != "http":
        print("Address should start with http or https")
        sys.exit(0)
    command_chain=""
    print "INFO: Starting dirb scan for " + address
    folder = '/usr/share/dirb/wordlists/vulns/'
    for wordfile in os.listdir(folder):
        wordlist = folder+wordfile
        if wordlist[-3:] == "txt":
            outfile = str(address)+str(".dirb")
            outfile = outfile.strip('http://')
            outfile = outfile.strip('https://')
            url = address
            out_put_files.append(outfile)
            command_chain += "dirb %s %s -o %s -r -S &" % (url, wordlist, outfile)
    t = threading.Thread(target=dirb_thread, args=(command_chain, ""))
    t.start()
    big_command = "xterm -e \"dirb %s %s -o %s -r \"; &" % (url, "/usr/share/dirb/wordlists/big.txt", outfile)
    t = threading.Thread(target=dirb_thread, args=(big_command, ""))
    t.start()

def dirb_analyze():
	files = [f for f in os.listdir('.') if os.path.isfile(f)]
	for f in files:
		if f[-4:] == "dirb":
			os.system('sort -u '+f)
			with open(f+'-results.txt', 'w') as outfile:
				with open(f) as infile:
					outfile.write('#############    '+f + '    #############\n')
					for line in infile:
						if "DIRECTORY" in line or "+" in line:
							outfile.write(line)
					outfile.write('#########################################\n')
			os.system('sort -u '+f+'-results.txt')
#dirb_analyze()