#!/usr/bin/env python
#
__author__ = 'admanne'
import os
import os.path
import sys
import datetime
import time
import threading

if len(sys.argv) != 2:
    print "Usage: null_httpfuzz address "
    sys.exit(0)


def date_time_stamp():
    r = str(datetime.datetime.now().strftime("%Y-%m-%d_%H%M%S")).rstrip()
    return r


if len(sys.argv) != 2:
    print "Usage: null_httpfuzz address "
    sys.exit(0)


##### MAKE DIRB LIST

dirb_file = "/root/lists/DirbMegaList.txt"
os.system("rm "+dirb_file)

os.system("mkdir ~/lists")
os.system("for i in `ls /usr/share/dirb/wordlists/vulns/`; do cat /usr/share/dirb/wordlists/vulns/$i >> "+dirb_file+"; done;")
os.system("for i in `ls /usr/share/dirb/wordlists/`; do cat /usr/share/dirb/wordlists/$i >> "+dirb_file+"; done;")

def getCleanList(dirty_list):
    clean_list = []

    for item in dirty_list:
        clean_text = item
        clean_text = clean_text.rstrip('\r\n')
        clean_text = clean_text.rstrip('\r')
        clean_text = clean_text.rstrip('\n')
        clean_text = clean_text.rstrip('\r')

        clean_list.append(clean_text)

    clean_list.sort()
    clean_list = list(set(clean_list))
    clean_list.sort()

    return clean_list

List = open(dirb_file).readlines()
clean = getCleanList(List)

os.system("rm "+dirb_file)

open_dirb_file = open(dirb_file, "w")

for item in clean:
    open_dirb_file.write(item+"\n")

open_dirb_file.close()

print (dirb_file + " created! ")

#####


address = str(sys.argv[1])
output = date_time_stamp() + ".txt"

if address[:4] != "http":
    print "http?"
    sys.exit(0)


def dirb_thread(command_chain, blank):
    os.system(command_chain)


# Dirb list made from;
# for i in `ls /usr/share/dirb/wordlists/vulns/`; do echo "cat $i >> ~/lists/DirbMegaList.txt"; done;
# for i in `ls /usr/share/dirb/wordlists`; do echo "cat $i >> ~/lists/DirbMegaList.txt"; done;


#  for i in `ls /usr/share/dirb/wordlists/vulns/`; do cat /usr/share/dirb/wordlists/vulns/$i >> ~/lists/DirbMegaList.txt; done;
#  for i in `ls /usr/share/dirb/wordlists/`; do cat /usr/share/dirb/wordlists/$i >> ~/lists/DirbMegaList.txt; done;




cmd = 'xterm -geometry 100x10+10+50 -e "dirb ' + address + ' /root/lists/dirb/DirbMegaList.txt -w -o dirb-' + output + '"&'
os.system(cmd)

cmd = 'xterm -geometry 100x10+10+250 -e "'
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/apache.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/cgis.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/coldfusion.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/dirTraversal-nix.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/dirTraversal.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/dirTraversal-win.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/domino.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/fatwire_pagenames.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/fatwire.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/frontpage.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/iis.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/iplanet.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/jrun.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/netware.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/oracle9i.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/sharepoint.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/sql_inj.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/sunas.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/tests.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/tomcat.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/vignette.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/weblogic.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/websphere.txt --hc 400,401,403,404 -o html " + address + "/FUZZ 2>> wfuzz-" + output + ".html;"
cmd += '"&'

os.system(cmd)









