#!/usr/bin/env python
__author__ = 'admanne'
import sys
import os

if len(sys.argv) != 3:
    print "<address-range> <ports>"
    print "Example:  null_enum_mssql 192.168.15.200-254 1433"
    sys.exit(0)

address = sys.argv[1].strip()
port = sys.argv[2].strip()
enum = (
    "xterm -e \"nmap -sV -Pn -vv -p %s --script="
    "ms-sql-brute,"
    "ms-sql-config,"
    "ms-sql-dac,"
    "ms-sql-dump-hashes,"
    "ms-sql-empty-password,"
    "ms-sql-hasdbaccess,"
    "ms-sql-info,"
    "ms-sql-query,"
    "ms-sql-tables,"
    "ms-sql-xp-cmdshell"
    " -oX 'enum_mssql_%s.xml' -oN 'enum_mssql_%s.nmap' %s\"" % (
        port, address, address, address)
)
print enum
os.system(enum)
