#!/usr/bin/python
__author__ = 'admanne'
import sys
import os

if len(sys.argv) != 2:
    print "<address-range>"
    print "Example:  null_enum_metasploit 192.168.15.200-254"
    sys.exit(0)

address = sys.argv[1].strip()
# Enum
enum = ("xterm -e \"nmap -sV -sT -Pn -vv --script="
	"metasploit-info,"
	"metasploit-xmlrpc-brute,"
	"metasploit-msgrpc-brute"
    " --script-args=unsafe=1 -oX 'enum_metasploit_%s.xml' -oN 'enum_metasploit_%s.nmap' %s ; bash\" &" % (address, address, address))
print(enum)
os.system(enum)