#!/usr/bin/python
#
__author__ = 'admanne'
import os
import os.path
import sys
import datetime
import time
import threading

def date_time_stamp():
    r = str(datetime.datetime.now().strftime("%Y-%m-%d_%H%M%S")).rstrip()
    return r

if len(sys.argv) != 2:
    print "Usage: null_wfuzz address output"
    sys.exit(0)

address = str(sys.argv[1])
if address[:4] != "http":
	print "http?"
	sys.exit(0)

output = date_time_stamp()+".txt"

print(address)
print(output)
cmd =  'xterm -e "'
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/apache.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/cgis.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/coldfusion.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/dirTraversal-nix.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/dirTraversal.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/dirTraversal-win.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/domino.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/fatwire_pagenames.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/fatwire.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/frontpage.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/iis.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/iplanet.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/jrun.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/netware.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/oracle9i.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/sharepoint.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/sql_inj.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/sunas.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/tests.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/tomcat.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/vignette.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/weblogic.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += " wfuzz -c -z file,/usr/share/wfuzz/wordlist/vulns/websphere.txt --hc 400,401,403,404 -o html "+address+"/FUZZ 2>> wfuzz-"+output+".html;"
cmd += '"&'

os.system(cmd)