#!/usr/bin/python
__author__ = 'admanne'
import sys
import os

if len(sys.argv) != 2:
    print "<address-range>"
    print "Example:  null_enum_vnc 192.168.15.200-254"
    sys.exit(0)

address = sys.argv[1].strip()
# Enum
enum = (
    "xterm -e \"nmap -sV -sT -Pn -vv -p 5900 --script="
	"realvnc-auth-bypass,"
	"vnc-brute,"
	"vnc-info "
    "--script-args=unsafe=1 -oX 'enum_vnc_%s.xml' -oN 'enum_vnc_%s.nmap' %s\"" % (
        address, address, address))
print enum
os.system(enum)
# /usr/share/nmap/scripts