#!/usr/bin/python
__author__ = 'admanne'
import sys
import os

if len(sys.argv) != 3:
    print "<address-range> <ports>"
    print "Example:  null_enum_mysql 192.168.15.200-254 3306"
    sys.exit(0)

address = sys.argv[1].strip()
port = sys.argv[2].strip()
# Enum
os.system(
    "xterm -e \"nmap -sV -sT -Pn -vv -p %s --script="
    "mysql-audit,"
	"mysql-brute,"
	"mysql-databases,"
	"mysql-dump-hashes,"
	"mysql-empty-password,"
	"mysql-enum,"
	"mysql-info,"
	"mysql-query,"
	"mysql-users,"
	"mysql-variables,"
	"mysql-vuln-cve2012-2122"
    " -oX 'enum_mysql_%s.xml' -oN 'enum_mysql_%s.nmap' %s\" &" % (
        port, address, address, address))