#!/usr/bin/env python
__author__ = 'admanne'
import sys
import os

if len(sys.argv) != 2:
    print "null_snmpwalk <address>"
    sys.exit(0)

address = sys.argv[1].strip()
# Enum users
os.system('snmpwalk -c public -v1 ' + str(address) + ' 1.3.6.1.4.1.77.1.2.25')
#Enum running processes
os.system('snmpwalk -c public -v1 ' + str(address) + ' 1.3.6.1.2.1.25.4.2.1.2')
#enum open tcp ports
os.system('snmpwalk -c public -v1 ' + str(address) + ' 1.3.6.1.2.1.6.13.1.3')
#enum installed software
os.system('snmpwalk -c public -v1 ' + str(address) + ' 1.3.6.1.2.1.25.6.3.1.2')