#!/usr/bin/env python
__author__ = 'admanne'
import sys
import os

if len(sys.argv) != 2:
    print "<address-range>"
    print "Example:  null_enum_smb 192.168.15.200-254"
    sys.exit(0)

address = sys.argv[1].strip()
# Enum
enum = (
    "xterm -e \"nmap -sV -sT -Pn -vv -p 139,445 --script="
    "smb-brute,"
    "smb-check-vulns,"
    "smb-enum-domains,"
    "smb-enum-groups,"
    "smb-enum-processes,"
    "smb-enum-sessions,"
    "smb-enum-shares,"
    "smb-enum-users,"
    "smb-mbenum,"
    "smb-os-discovery,"
    "smb-print-text,"
    "smb-psexec,"
    "smb-security-mode,"
    "smb-server-stats,"
    "smb-system-info,"
    "smbv2-enabled,"
    "smb-vuln-ms10-054,"
    "smb-vuln-ms10-061,"
    "smb-ls,"
    "smb-flood "
    "--script-args=unsafe=1 -oX 'enum_smb_%s.xml' -oN 'enum_smb_%s.nmap' %s\"" % (
        address, address, address))
print enum
os.system(enum)