#!/usr/bin/env python
import socket
import sys


__author__ = 'mannea'

if len(sys.argv) != 3:
    print "Usage: null_smtp <ip address> <string/address>"
    sys.exit(0)

address = sys.argv[1]
name = sys.argv[2]

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
connect = sock.connect((address, 25))
banner = sock.recv(1024)
print(banner)
sock.send('HELO null.org \r\n')
result = sock.recv(1024)
print(result)
sock.send('VRFY ' + name.strip() + '\r\n')
result = sock.recv(1024)
print(result)
if ("not implemented" in result) or ("disallowed" in result):
    sys.exit("INFO: VRFY Command not implemented on " + sys.argv[1])
if (("250" in result) or ("252" in result) and ("Cannot VRFY" not in result)):
    print "[*] SMTP VRFY Account found on " + sys.argv[1] + ": " + name.strip()
sock.close()