#!/usr/bin/python
__author__ = 'mannea'
#
import random
import sys
import os

if len(sys.argv) != 3:
    print "randomizeList <in file> <out file>"
    sys.exit(0)

in_file = sys.argv[1].strip()
out_file = sys.argv[2].strip()

with open(in_file, 'r') as source:
    data = [(random.random(), line) for line in source]
data.sort()

if os.path.isfile(out_file):
    os.system('rm ' + out_file)

with open(out_file, 'w') as target:
    for _, line in data:
        target.write(line)